### ISSUE TITLE
Please add Diorite compatibility

### ISSUE THREAD

**Issue by Willow-Systems** [huntboom/PebbleGPT#2]
The app currently isn't available for Diorite (Pebble 2). As it is compatible with aplite there should be no issue just adding diorite to package.json

Thanks for this app, it's a great idea!

**Comment by huntboom** [comment]
Diorite compatibility added, thanks so much and long live Pebble!

**Comment by huntboom** [comment]
Diorite compatibility added, thanks so much and long live Pebble!
