### ISSUE TITLE
Awaiting response too long

### ISSUE THREAD

**Issue by MitoKafander** [huntboom/PebbleGPT#3]
![16889918955114218646553898845134](https://github.com/huntboom/PebbleGPT/assets/60237079/89522f14-3faa-425f-93f9-c62cd6d4a9fc)
Cannot get past this screen. "Message sent to openai, awaiting response..."

**Comment by huntboom** [comment]
Wait times vary based on Internet connections, OpenAI, and the size of the message you're receiving. I try and test my internet connection with simple messages like "what's 1+1" etc as the response is usually near instant for these kinds of messages.
